development:
  stripe_publishable_key: pk_test_51NY6dASD4Fra99nqHAKIV6Ekta38GEohBrnWkGRso18xM6i7YuiP83YVNLlcqPQNw2RzEHaEgu49qmaTxhFaWW0u00dSb5EjzG
  stripe_secret_key: sk_test_51NY6dASD4Fra99nqy4Dkzj8sdjRe04MjCP7xxuPEVdhubpnoSYL7JkEy3EY0EIGZyuJ9wmj5EepSrUFM8QPJD8HJ00JSHpDuF7

test:
  stripe_publishable_key: pk_test_51NY6dASD4Fra99nqHAKIV6Ekta38GEohBrnWkGRso18xM6i7YuiP83YVNLlcqPQNw2RzEHaEgu49qmaTxhFaWW0u00dSb5EjzG
  stripe_secret_key: sk_test_51NY6dASD4Fra99nqy4Dkzj8sdjRe04MjCP7xxuPEVdhubpnoSYL7JkEy3EY0EIGZyuJ9wmj5EepSrUFM8QPJD8HJ00JSHpDuF7

production:
  stripe_publishable_key: pk_test_51NY6dASD4Fra99nqHAKIV6Ekta38GEohBrnWkGRso18xM6i7YuiP83YVNLlcqPQNw2RzEHaEgu49qmaTxhFaWW0u00dSb5EjzG
  stripe_secret_key: sk_test_51NY6dASD4Fra99nqy4Dkzj8sdjRe04MjCP7xxuPEVdhubpnoSYL7JkEy3EY0EIGZyuJ9wmj5EepSrUFM8QPJD8HJ00JSHpDuF7
